class Definitions:
    TR_CB_STATS_URL = "https://www.teamrankings.com/ncaa-basketball"
    END_DATES = {
        2008: 20,
        2009: 19,
        2010: 18,
        2011: 17,
        2012: 15,
        2013: 21,
        2014: 20,
        2015: 19,
        2016: 17,
        2017: 16,
        2018: 15,
        2019: 21,
        2021: 19,
        2022: 17,
        2023: 16,
        2024: 21,
    }
    TR_RATINGS = [
        "predictive",
        "neutral",
        "schedule-strength",
        "future-sos",
        "season-sos",
        "sos-basic",
        "last-5-games",
        "last-10-games",
        "luck",
        "consistency",
    ]
    TR_STATS = [
        "points-per-game",
        "average-scoring-margin",
        "offensive-efficiency",
        "floor-percentage",
        "1st-half-points-per-game",
        "2nd-half-points-per-game",
        "shooting-pct",
        "free-throw-pct",
        "true-shooting-percentage",
        "field-goals-made-per-game",
        "field-goals-attempted-per-game",
        "offensive-rebounds-per-game",
        "defensive-rebounds-per-game",
        "total-rebounding-percentage",
        "blocks-per-game",
        "steals-per-game",
        "assists-per-game",
        "assists-per-possession",
        "turnovers-per-game",
        "personal-fouls-per-game",
        "opponent-points-per-game",
        "opponent-average-scoring-margin",
        "defensive-efficiency",
        "opponent-floor-percentage",
        "opponent-1st-half-points-per-game",
        "opponent-2nd-half-points-per-game",
        "opponent-shooting-pct",
        "opponent-free-throw-pct",
        "opponent-true-shooting-percentage",
        "opponent-field-goals-made-per-game",
        "opponent-field-goals-attempted-per-game",
        "opponent-offensive-rebounds-per-game",
        "opponent-defensive-rebounds-per-game",
        "opponent-blocks-per-game",
        "opponent-steals-per-game",
        "opponent-assists-per-game",
        "opponent-assists-per-possession",
        "opponent-turnovers-per-game",
        "opponent-personal-fouls-per-game",
        "possessions-per-game",
        "extra-chances-per-game",
    ]
